RHYTHM_LABELS = {
    "sinus_rhythm": ["sinus rhythm", "sinus rhythm normal"],
    "sinus_bradycardia": ["sinus bradycardia", "bradycardia"],
    "sinus_tachycardia": [
        "sinus tachycardia", 
        "tachycardia",
        "supraventricular tachycardia",
        "svt",
        "ectopic atrial rhythm",
        "wandering atrial pacemaker",
        "ventricular tachycardia",
        "wide complex tachycardia", 
        "wideqrs tachycardia", 
        "wide qrs tachycardia",
    ],
    "sinus_arrhythmia": [
        "sinus arrhythmia", 
        "slow sinus arrhythmia",
        "undetermined rhythm",
        "unclassified ecg",
        "unknown rhythm",
    ],
    "atrial_fibrillation": ["atrial fibrillation", "fibrillation", "aflutterfibrillation"],
    "atrial_flutter": ["atrial flutter", "aflutter"],
    "junctional_rhythm": ["junctional rhythm", "accelerated junctional rhythm"],
    "ventricular_paced_rhythm": [
        "ventricular paced rhythm",
        "ventricular paced",
        "ventricularpaced",
        "ventricular pacing",
    ],
}

CONDUCTION_LABELS = {
    "right_bundle_branch_block": [
        "rbbb", 
        "right bundle branch block",
    ],
    "left_bundle_branch_block": [
        "lbbb", 
        "left bundle branch block", 
        "ilbbb", 
        "incomplete left bundle branch block",
        "intraventricular conduction delay",
        "ivcd",
        "intermittent conduction defect",
        "aberrant conduction",
        "aberrantly conducted",
        "aberrant complex",
        "aberrant ventricular conduction",
        "wpw pattern",
        "wolffparkinsonwhite",
        "ventricular preexcitation",
        "vent preexcit",
    ],
    "av_block": [
        "av block", 
        "degree av block", 
        "st degree av block", 
        "nd degree av block", 
        "rd degree av block", 
        "complete av block", 
        "wenckebach", 
        "mobitz",
    ],
    "left_anterior_fascicular_block": [
        "left anterior fascicular block", 
        "anterior fascicular block", 
        "lafb",
        "left posterior fascicular block",
        "posterior fascicular block",
        "lpfb",
    ],
}

STRUCTURAL_LABELS = {
    "left_ventricular_hypertrophy": [
        "left ventricular hypertrophy",
        "ventricular hypertrophy",
        "lvh",
        "voltage criteria for left ventricular hypertrophy",
        "abnormally high qrs voltages",
        "high qrs voltage",
        "abnormally high sv rv",
    ],
    "right_ventricular_hypertrophy": ["right ventricular hypertrophy", "rvh"],
    "left_atrial_enlargement": [
        "left atrial enlargement", 
        "left atrial abnormality", 
        "lae", 
        "abnormal p terminal force",
        "biatrial enlargement",
        "biatrial abnormality",
        "abnormal p waves",
        "p wave abnormality",
    ],
    "right_atrial_enlargement": [
        "right atrial enlargement",
        "right atrial abnormality",
        "rae",
        "tall inferior p waves",
        "abnormally tall p",
        "abnormally high p amplitudes",
        "hyperkalemia",
        "tall t waves consider hyperkalemia",
        "tall t waves suggest hyperkalemia",
    ],
    "axis_deviation": [
        "axis deviation",
        "left axis deviation",
        "right axis deviation",
        "extreme axis deviation",
        "abnormal extreme qrs axis deviation",
    ],
}

REPOLARIZATION_LABELS = {
    "st_elevation": [
        "st elevation",
        "st elev",
        "early repolarization",
        "early repol",
    ],
    "prolonged_qt": ["prolonged qt", "prolonged qt interval"],
}

ISCHEMIA_INFARCT_LABELS = {
    "myocardial_injury": [
        "myocardial injury",
        "injury",
        "st elevation consider",
        "cannot rule out myocardial injury",
        "pericarditis",
        "suggests acute pericarditis",
        "strongly suggests pericarditis",
        "post operative pericarditis",
    ],
    "infarct_pattern": [
        "infarct",
        "infarction",
        "inferior infarct",
        "anterior infarct",
        "lateral infarct",
        "septal infarct",
        "posterior infarct",
        "anterolateral infarct",
        "anteroseptal infarct",
        "extensive infarct",
        "age undetermined",
        "age indeterminate",
        "possibly acute",
        "probably acute",
        "acute infarct",
        "old infarct",
        "recent infarct",
        "abnormal q suggests",
        "abnormal inferior q waves",
    ],
}

ECTOPY_LABELS = {
    "pvcs": [
        "pvcs", 
        "ventricular premature", 
        "ventricular extrasystoles", 
        "multifocal pvcs", 
        "frequent pvcs", 
        "interpolated pvcs",
        "ventricular bigeminy",
        "bigeminy",
        "ventricular trigeminy",
        "trigeminy",
        "ventricular couplets",
        "couplets",
    ],
    "pacs": [
        "pacs", 
        "atrial premature", 
        "supraventricular extrasystoles", 
        "atrial extrasystoles",
        "supraventricular bigeminy",
    ],
}

IMPRESSION_LABELS = {
    "normal_ecg": [
        "normal ecg",
        "probable normal",
        "normal variant",
        "probable normal variant",
        "within normal limits",
        "summary normal",
        "available leads normal",
        "technical error",
        "technically unsatisfactory",
        "analysis error",
        "all leads are missing",
        "data quality may affect",
        "lead reversal",
        "arm lead reversal",
        "limb lead reversal",
        "suggests dextrocardia",
    ],
    "borderline_ecg": [
        "borderline ecg",
        "nonspecific borderline ecg",
        "borderline abnormal",
        "summary borderline",
    ],
    "abnormal_ecg": [
        "abnormal ecg",
        "nonspecific abnormal ecg",
        "undetermined abnormal ecg",
        "summary abnormal",
    ],
}

report_label_map = {
    **RHYTHM_LABELS,
    **CONDUCTION_LABELS,
    **STRUCTURAL_LABELS,
    **REPOLARIZATION_LABELS,
    **ISCHEMIA_INFARCT_LABELS,
    **ECTOPY_LABELS,
    **IMPRESSION_LABELS,
}